### ISSUE TITLE
Need to turn red LED when any error occured

### ISSUE THREAD

**Issue by usaguerrilla** [usaguerrilla/hab#1]
Should stay on until board reset.
Do we need to reset board on error? If so which errors merit reset?

Candidates:
- buffer for incoming GPS messages is full and isn't getting any free spots in a long time
- failed to send radio message for too many times

**Comment by stcarlso** [comment]
I think that we have this one mostly addressed. The fault ISR turns on the red LED, but just locks up (which is bad). If we reset immediately, the red LED will never turn on.

Startup errors will turn the LED red, but I think that the GPS status should be related to the LED color so we know when it is running and good to launch. Buffer for messages could definitely get filled with garbage since the ISR is based on CRLF termination. In that case I would argue for directly overwriting when full to avoid crashing.

How can we "fail" to send a radio message?
