### ISSUE TITLE
i2c service shouldn't bail if one device isn't present

### ISSUE THREAD

**Issue by usaguerrilla** [usaguerrilla/hab#20]
you should work with devices you have.
if one is not present ignore it.

**Comment by stcarlso** [comment]
HABService looks for the devices on boot and dies if they cannot be initialized. After that, if the devices fail when running, HAB Service retries later. This was useful during debugging as I could set a breakpoint that would only be hit if initialization fails.

Since HABService dying causes IoT to blue screen, I can easily change this to ignore the bad device(s). However, since the Pi has no controllable indicator LEDs, I would have no way of indicating this to the user. How can I indicate this so we can fix the issue if it recurs on launch day?
